ame: Install mdbook and dependencies

description: Install the mdbook with the dependencies we need.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: mdbook-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    # The --locked flag is important for reproducible builds. It also
    # avoids breakage due to skews between mdbook and mdbook-svgbob.
    - name: Install mdbook
      run: cargo install mdbook --locked --version 0.4.27
      shell: bash

    - name: Install mdbook-keeper
      run: cargo install mdbook-keeper --locked --version 0.2.4
      shell: bash

    - name: Install mdbook-cmdrun
      run: cargo install mdbook-cmdrun --locked --version 0.5.0
      shell: bash

    - name: Install cargo-expand
      run: cargo install cargo-expand
      shell: bash

    - name: Install i18n-helpers
      run: cargo install --git https://github.com/google/comprehensive-rust i18n-helpers
      shell: bash

    - name: Build macrokata
      run: cargo build --bin macrokata
      shell: bash
